### ISSUE TITLE
Paper-equivalent implementation

### ISSUE THREAD

**Issue by tarepan** [patrickltobing/cyclevae-vc-neuralvoco#4]
## Summary
Which version of implementation is equivalent to the paper model?  

## Main
Thanks for open-source great VC system.  
I am trying to reproduce the result in CycVAE-MWDLP-VC paper.  

Now there are v3.0 and v3.1 of implementation.  
Which is the exact implementation of the paper?  
v3.0 is "pre-publish" & v3.1 is "the paper" model?  
or, v3.0 is "the paper" & v3.1 is "improved" model?

Again, thanks for great open-source VC system.

**Comment by patrickltobing** [comment]
Thank you for your helpful feedback.
I'm sorry for the confusion on the versioning.

Please use v3.1 as the equivalent paper implementation,
where the latest tested working commit was 1ef01de.

The related working demo and samples will be updated soon.
Again, sorry and thanks for your comments.

**Comment by tarepan** [comment]
v3.1, OK.  
Thank you very much!
